-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 20:50:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ElBuenSabor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ElBuenSabor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ElBuenSabor` DEFAULT CHARACTER SET utf8 ;
USE `ElBuenSabor` ;

-- -----------------------------------------------------
-- Table `ElBuenSabor`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ElBuenSabor`.`Domicilio` (
  `idDomicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ElBuenSabor`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ElBuenSabor`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `Cliente-Domicilio`
    FOREIGN KEY (`idCliente`)
    REFERENCES `ElBuenSabor`.`Domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ElBuenSabor`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ElBuenSabor`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `Usuario-Cliente`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ElBuenSabor`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
